name: Cypress Payt

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Install dependencies
      run: npm install

    - name: Set Cypress environment variables
      run: |
        echo "{\"user_name\": \"$USER_NAME\", \"user_password\": \"$USER_PASSWORD\", \"user_name_error\": \"$USER_NAME_ERROR\", \"user_password_error\": \"$USER_PASSWORD_ERROR\"}" > cypress.env.json
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        USER_NAME_ERROR: ${{ secrets.USER_NAME_ERROR }}
        USER_PASSWORD_ERROR: ${{ secrets.USER_PASSWORD_ERROR }}

    - name: Verificar conteúdo de cypress.env.json
      run: cat cypress.env.json


    - name: Run Cypress tests
      run: npx cypress run --browser chrome
