name: Cypress Payt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Install dependencies
      run: npm install

    - name: Set Cypress environment variables
      run: |
        echo "{\"user_name\": \"$CYPRESS_user_name\", \"user_password\": \"$CYPRESS_user_password\", \"user_name_error\": \"$CYPRESS_user_name_error\", \"user_password_error\": \"$CYPRESS_user_password_error\"}" > cypress.env.json

    - name: Run Cypress tests
      run: npx cypress run --browser chrome
